version: "3"
services:
  web_app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=redis_db
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/log/nginx

  redis_db:
    image: redis:alpine
    read_only: true
    tmpfs:
      - /var/run/redis
      - /tmp
